server:
  port: 9090

spring:
  application:
    name: springboot-rocketmq

# rocketmq server地址，集群封号号分隔
rocketmq:
  name-server: 182.xx.xxx.245:9876
  producer:
    group: ${spring.application.name} # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
    send-message-timeout: 3000 # 消息发送超时时长，默认3s
    max-message-size: 4096 # 消息最大长度 默认 1024 * 4 (4M)
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2
    retry-next-server: false # 发送消息给broker时，如果发送失败，是否重试另外一台broker。默认为false
