nacos:
  config:
    server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  client:
    default-to-properties: true
    default-config: myconf
    config:
      myconf:
        connectTimeout: 8000
        readTimeout: 120000
  okhttp:
    enabled: true
  httpclient:
    enabled: true

